#!/bin/bash -e

REPO_PATH=git@github.com:tgockel/nginxconfig.git
HTML_PATH=build/doc/html
COMMIT_AUTHOR="Documentation Builder <travis@gockelhut.com>"
CHANGESET=$(git rev-parse --verify HEAD)

make clean-doxygen
mkdir -p ${HTML_PATH}
git clone -b gh-pages "${REPO_PATH}" --single-branch ${HTML_PATH}
make doxygen

echo "Creating git changeset..."
cd ${HTML_PATH}
git add .
#git commit --author="${COMMIT_AUTHOR}" -m "Automated documentation build for changeset ${CHANGESET}."
#git push origin gh-pages
cd -
